.husky/commit-msg
.husky/pre-commit

> #9 
husky를 통해 브랜치의 이슈번호를 자동으로 commit에 달아줄 수 있도록 설정했습니다.
https://github.com/user-attachments/assets/169984d4-ae69-405e-bdd8-3858953d7bf6

chore(#9): husky 브랜치 이슈번호 자동으로 commit에 라벨링

---

apps/frontend/src/feature/History/index.tsx
apps/frontend/src/widget/HistoryList.tsx

#32
```tsx
// AS-IS
<h1 className={cn('', className)} {...props}>
{title}
</h1>
// TO-BE
<Heading size="sm" className={cn('', className)} {...props}>
{title}
</Heading>
```

Refactor(#32): typography design 추가로 인한 기존 History, CodeView feature refactor

---

apps/frontend/src/app/style/github.css
apps/frontend/src/feature/Comment/Comment.tsx
apps/frontend/src/feature/Comment/CommentCard.tsx
apps/frontend/src/feature/Comment/CommentForm.tsx
apps/frontend/src/feature/Comment/index.tsx
packages/design/package.json
packages/design/src/components/index.tsx
packages/design/src/components/ui/tabs.tsx

#29
Comment 컴포넌트는 User Feature 컴포넌트와 결합된 부분이 보입니다. 
현재는 기본적인 컴포넌트 구성으로 작업했지만 추후에는 분리가 필요해 보입니다.
- CommentValue interface 내부 author 타입 선언

Feature #29 comment UI

---

apps/backend/src/app.module.ts
apps/backend/src/config/typeorm.config.ts

#42
이전 브랜치에서 공개적으로 올렸던 db정보를 env파일로 관리하여 노출 방지

fix(#42): db config env파일로 관리

---

apps/frontend/src/shared/components/AsyncBoundary/AsyncBoundary.tsx
apps/frontend/src/shared/components/AsyncBoundary/index.ts
apps/frontend/src/shared/components/ErrorBoundary/ErrorBoundary.test.tsx
apps/frontend/src/shared/components/ErrorBoundary/ErrorBoundary.tsx
apps/frontend/src/shared/components/ErrorBoundary/index.ts
apps/frontend/src/shared/hooks/useOverlay/OverlayProvider.tsx
apps/frontend/src/shared/hooks/useOverlay/index.tsx
apps/frontend/src/shared/hooks/useOverlay/useOverlay.test.tsx
apps/frontend/src/shared/hooks/useOverlay/useOverlay.ts

#57 
- useOverlay hooks
- ErrorBoundary
- AsyncBoundary
AsyncBoundary의 경우 내부에 ErrorBoundary와 Suspense를 사용하기 때문에 테스트 코드를 추가하지 않았습니다.

Feature #57 ErrorBoundary, AsyncBoundary, useOverlay

---

apps/frontend/package.json
apps/frontend/public/mockServiceWorker.js
apps/frontend/src/app/main.tsx
apps/frontend/src/app/mock/browser.ts
apps/frontend/src/app/mock/gistResolvers.ts
apps/frontend/src/app/mock/handlers.ts
apps/frontend/src/app/mock/lotusResolvers.ts
apps/frontend/src/app/mock/userResolvers.ts
apps/frontend/src/page/(main)/lotus/index.lazy.tsx
pnpm-lock.yaml

> closed #64
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- msw 세팅하기
- api 명세서에 따라서 resolvers 정의하기

Feature #64: msw 세팅하기

---

apps/backend/package.json
apps/backend/src/main.ts

close #69 
- swagger 추가
- :3000/swagger 로 접속(추후에 서버에 추가되어도 동일)
- 아직 api에 대한 태그들이나 명세를 추가하지 않았기 떄문에 내용이 충분하지 않은 것 같습니다. 스웨거에 desc를 추가하는 작업들이 필요할 것 같습니다.

swagger 추가

---

apps/frontend/src/app/mock/gistResolvers.ts
apps/frontend/src/feature/Lotus/api.ts
apps/frontend/src/feature/Lotus/query.ts
apps/frontend/src/feature/User/api.ts
apps/frontend/src/feature/User/query.ts
apps/frontend/src/page/(main)/lotus/create/index.lazy.tsx
apps/frontend/src/shared/components/TagInput.tsx
apps/frontend/src/widget/LotusCreate/LotusCreateForm.tsx
apps/frontend/src/widget/LotusCreate/SuspenseGistFiles.tsx
apps/frontend/src/widget/LotusCreate/SuspenseUserGistSelect.tsx
apps/frontend/src/widget/LotusUpdateButton.tsx

> closed #83
> Lotus create 페이지 구현 및 mocking 적용하기
https://github.com/user-attachments/assets/d113d90e-bb7e-48c9-817c-6efcc6ae9e20

Feature #83: lotus create

---

apps/frontend/src/app/query/QueryProvider.tsx
apps/frontend/src/app/router/routeTree.gen.ts
apps/frontend/src/feature/History/api.ts
apps/frontend/src/feature/Lotus/api.ts
apps/frontend/src/feature/User/api.ts
apps/frontend/src/feature/User/query.ts
apps/frontend/src/feature/User/utils/isAuthUser.ts
apps/frontend/src/page/(main)/lotus/create/index.tsx
apps/frontend/src/page/(main)/user/index.tsx
apps/frontend/src/shared/utils/isAuthUser.ts
apps/frontend/src/widget/LotusUpdateForm.tsx
packages/design/src/components/ui/pagination.tsx

> closed #87
- fetch -> axios로 변경하기
- 수정하기 버튼 스타일 변경하기
- cursor 적용하기
- Authenticated Routes 적용하기
https://github.com/user-attachments/assets/e246a2c0-38f8-4d07-bc0e-64bc3b7b936c

Feature #87: axios, Authenticated Routes, cursor 적용하기

---

apps/frontend/src/shared/hooks/useOverlay/OverlayController.tsx
apps/frontend/src/shared/hooks/useOverlay/useOverlay.test.tsx
apps/frontend/src/shared/hooks/useOverlay/useOverlay.tsx
apps/frontend/src/shared/hooks/useTimer/index.ts
apps/frontend/src/shared/hooks/useToast/Toast.tsx
apps/frontend/src/shared/hooks/useToast/index.tsx
apps/frontend/src/shared/hooks/useToast/useToast.tsx
apps/frontend/src/widget/LotusCodeInput/CodeRunButton.tsx
apps/frontend/src/widget/LotusDeleteButton.tsx
apps/frontend/src/widget/LotusUpdateButton.tsx

> closed #91 
- useOverlay 훅 리팩터링
- 언마운트 할때 언마운트 에니메이션이 보이지 않는 문제 해결
- Toast 컴포넌트
- 토스트를 보여줄 컴포넌트 
- 타이머 내부에서 관리 
- useToast 훅
- toast를 마운트하는 훅 
- useTimer 훅
- toast 타이머 관리 훅 
toast hover 할때 타이머 일시정지
디자인은 레이아웃만 만들어둔 상태입니다. 필요하다면 수정해야합니다.
타이머를 setInterval을 통해서 돌리고 있기 때문에 성능문제가 발생할 수 있습니다. 추후에 개선이 필요합니다.

Feature #91 toast & refactor useOverlay

---

.github/workflows/fe-ci.yml

closed #94 
- main에 pr, push 할때 ci
- release에 push할때 cd

Chore(#94):  ci, cd 나누기

---

apps/frontend/src/app/router/RouteProvider.tsx

#97
> tanstack router devtools dev 모드 일때만 사용하도록 설정하기

Feature #97: tanstack router devtools dev 모드 일때만 사용하기

---

.github/workflows/fe-ci.yml

Refactor(#94):  fe-ci 라벨 분기 설정

---

.github/workflows/be-cd.yml
.github/workflows/be-ci.yml
Dockerfile
apps/backend/src/auth/auth.service.ts
apps/backend/src/config/typeorm.config.ts
apps/backend/src/history/history.controller.ts
apps/backend/src/main.ts
apps/backend/src/user/user.controller.ts
apps/backend/src/user/user.service.ts
docker-compose.yml

close #98
서버배포전 main브랜치 api테스트를 위한 docker-compose작성

api 테스트용 docker-compose

---

apps/backend/src/docker/docker.controller.ts
apps/backend/src/gist/gist.service.ts
apps/backend/src/history/dto/history.pulbic.dto.ts
apps/backend/src/history/history.controller.ts
apps/backend/src/history/history.service.ts
apps/backend/src/lotus/dto/lotus.updateRequest.dto.ts
apps/backend/src/lotus/lotus.controller.ts
apps/backend/src/lotus/lotus.entity.ts
apps/backend/src/lotus/lotus.service.ts
apps/backend/src/user/user.controller.ts

> ex) close #105 
> query에서 number로 받는 데이터들 parseIntPipe 추가
> github login/callback 시 token 반환에서 redirect로 수정
> console.log 삭제
> lotus update 에러 수정
> page, size 기본 값 설정(Default Value Pipe)
> 시나리오 테스트(생성, 수정, 삭제, 로그인)

Feature #105 git oauth redirect url

---

apps/frontend/src/feature/user/util.ts
apps/frontend/src/page/(main)/lotus/create/index.tsx
apps/frontend/src/page/(main)/user/index.tsx

closed #125
tanstack router의 Authenticated Route 적용 시에 beforeLoad에서 refetchQueries가 잘 동작하지 않아서 refetchQueries -> fetchQuery로 변경하기
https://github.com/user-attachments/assets/bd27b0d9-a82e-403a-aba4-3d0c581dab7f

Fix #125: 새로고침 시에 로그인 상태 유지 못하는 에러 수정하기

---

apps/frontend/src/page/(main)/user/index.lazy.tsx
apps/frontend/src/widget/lotusList/SuspenseLotusPagination.tsx
apps/frontend/src/widget/lotusList/SuspenseUserLotusPagination.tsx
apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx
apps/frontend/src/widget/user/SuspenseUserLotusList.tsx

#117 
- SuspenseUserInfoBox skeleton
- SuspenseUserLotusList skeleton
- SuspenseUserLotusPagination skeleton
https://github.com/user-attachments/assets/ac0471f6-de4d-4471-b9ba-893fd5f1bba6

Feature #117 : 사용자 정보 페이지의 fallback ui 구현하기

---

apps/backend/src/history/history.controller.ts
apps/backend/src/lotus/lotus.controller.ts
apps/backend/src/lotus/lotus.service.ts

> close #129
> 비로그인 사용자도 public lotus 상세 페이지 조회 가능
> 비로그인 사용자도 public lotus 실행 가능
> tag 없는 lotus 안 보이는 버그 수정
- 비로그인 사용자도 public lotus 상세 페이지 조회 가능
- 비로그인 사용자도 public lotus 실행 가능
- tag 없는 lotus 안 보이는 버그 수정

Fix #129 비로그인 사용자 버그 수정 및 tag 버그 수정

---

apps/frontend/src/widget/lotusCodeRun/CodeRunButton.tsx
apps/frontend/src/widget/lotusUpdate/LotusUpdateButton.tsx

#138 
invalidateQueries에서 queryOptions 사용

Fix(#138):  invalidateQueries에서 queryOptions 사용

---

apps/backend/src/lotus/lotus.service.ts

> close #161 
> tag search는 주석 처리하고 title search로 변경(이유는 이슈 봐주세요)
> search 중복 코드 개선

Feature #161: search를 tag가 아닌 title로 하도록 수정

---

apps/frontend/src/page/(main)/lotus/$lotusId/index.lazy.tsx
apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
apps/frontend/src/widget/lotusDetail/SuspenseLotusEdit.tsx
apps/frontend/src/widget/lotusDetail/index.ts

#166 
> lotus detail에서 user token 에러로 인해 디테일 페이지가 전부 깨지는 문제 해결

Fix(#166):  lotus Edit버튼에서 user token 401 error 페이지 깨짐 해결

---

apps/frontend/src/feature/lotus/component.tsx
apps/frontend/src/widget/lotusDetail/SuspenseLotusDetail.tsx
apps/frontend/src/widget/lotusList/SuspenseLotusCardList.tsx

closed #176 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

Feature(#176):  lotus list, lotus detail에 gist 바로가기 추가

---

apps/frontend/src/widget/lotusList/SuspenseLotusList.tsx
apps/frontend/src/widget/lotusList/index.ts
apps/frontend/src/widget/user/SuspenseUserInfoBox.tsx

closed #198
- useInfoBox 디자인 변경하기
- lotus 목록 조회에서 보여줄 데이터가 없을 때 처리하기
- SuspenseLotusCardList -> SuspenseLotusList로 통일하기

Refactor #198: 사용자 정보 페이지 리팩토링
